# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # =======================================================================
  # Here we specify which box to use (in this case "centos/7") and NOT to 
  # update Virtualbox guest additions if any updates are available.
  # =======================================================================
  config.vm.box = "centos/7"
  config.vbguest.auto_update = false

  # =======================================================================
  # Specify provisioning script to use. This scripts automates setup process
  # for creating a box *similar* LAMP stack (excluding MySQL) (Linux Apache MySQL PHP)
  # =======================================================================
  config.vm.provision "shell", path: "./provision.sh"

  # ======================================================================
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # =======================================================================
  config.vm.network "forwarded_port", guest: 80, host: 8080

end
